# Use root/example as user/password credentials
version: '3.1'

services:
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf3
  adminer:
      image: adminer
      restart: always
      ports:
        - 8890:8080
      depends_on:
        - mysqldb