fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

cart:
    resource: "@CartBundle/Controller/"
    type:     annotation
    prefix:   /cart

app:
    resource: '@AppBundle/Controller/'
    type: annotation
