services:
#    cart.example:
#        class: CartBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  cart.product.handler:
    class: CartBundle\Forms\Handler\ProductHandler
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@form.factory"
      - "@request_stack"
