<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerXx4dxqw\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerXx4dxqw/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerXx4dxqw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXx4dxqw\appDevDebugProjectContainer();
